apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: routemode-de-tls
spec:
  secretName: routemode-de
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: routemode.de
  dnsNames:
    - routemode.de
    - www.routemode.de
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - routemode.de
          - www.routemode.de